CREATE TABLE `cricket_matches` (
    `match_id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `league_id` INT,
    `gender` ENUM('Male', 'Female'),
    `season_id` INT,
    `home_team_id` INT,
    `away_team_id` INT,
    `home_team_name` VARCHAR(120),
    `away_team_name` VARCHAR(120),
    `venue_id` INT,
    `result` VARCHAR(200),
    `man_of_the_match` VARCHAR(100),
    `toss_winner` INT,
    `toss_decision` ENUM('Bat', 'Field'),
    `winning_team` INT,
    `cricsheet_file_name` VARCHAR(20),
    `match_date` DATE,
    `match_date_multi` VARCHAR(120),
    `match_time` TIME,
    `is_reschedule` BOOLEAN DEFAULT FALSE,
    `is_abandoned` BOOLEAN DEFAULT FALSE,
    `is_neutral` BOOLEAN DEFAULT FALSE,
    `match_refrees` VARCHAR(100),
    `reserve_umpires` VARCHAR(100),
    `tv_umpires` VARCHAR(100),
    `umpires` VARCHAR(100),
    `date_added` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `last_update` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `match_end_time` DATETIME,
    `status` CHAR(2)
) ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

