CREATE TABLE `player_match_stats` (
    `match_id` INT NOT NULL,
    `season_id` VARCHAR(40) NOT NULL,
    `innings_id` VARCHAR(40) NOT NULL,
    `season_type` VARCHAR(40),
    `team_id` INT NOT NULL,
    `player_id` INT NOT NULL,
    `batting_order` INT,
    `runs_scored` INT,
    `balls_faced` INT,
    `dot_balls_played` INT,
    `singles` INT NULL DEFAULT NULL,
    `doubles` INT NULL DEFAULT NULL,
    `triples` INT NULL DEFAULT NULL,
    `fours_hit` INT NULL DEFAULT NULL,
    `sixes_hit` INT NULL DEFAULT NULL,
    `out_type` VARCHAR(40) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
    `out_fielder` VARCHAR(40) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
    `out_bowler` VARCHAR(40) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
    `is_batted` INT NULL DEFAULT NULL,
    `overs_bowled` VARCHAR(16) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
    `bowling_order` INT NULL DEFAULT NULL,
    `runs_conceded` INT NULL DEFAULT NULL,
    `balls_bowled` INT NULL DEFAULT NULL,
    `dots_bowled` INT NULL DEFAULT NULL,
    `wickets_taken` INT NULL DEFAULT NULL,
    `fours_conceded` INT NULL DEFAULT NULL,
    `sixes_conceded` INT NULL DEFAULT NULL,
    `extras_conceded` INT NULL DEFAULT NULL,
    `maiden_over` INT NULL DEFAULT NULL,
    `run_out` INT NULL DEFAULT NULL,
    `catches` INT NULL DEFAULT NULL,
    `stumpings` INT NULL DEFAULT NULL,
    `played_abandoned_matches` INT,
    `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`match_id`, `team_id`, `player_id`),
    FOREIGN KEY (`match_id`) REFERENCES `cricket_matches`(`match_id`),
    FOREIGN KEY (`team_id`) REFERENCES `teams`(`team_id`),
    FOREIGN KEY (`player_id`) REFERENCES `cricket_players`(`player_id`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
